### ISSUE TITLE
can you help me?

### ISSUE THREAD

**Issue by songwenhao123** [thfylsty/imagefusion_Perceptual_FusionGan#3]
Traceback (most recent call last):
  File "test.py", line 141, in <module>
    train_data_ir,train_data_vi=input_setup(i)
  File "test.py", line 95, in input_setup
    input_ir=(imread(data_ir[index])-127.5)/127.5
  File "test.py", line 29, in imread
    return imageio.imread(path, flatten=True, pilmode='YCbCr').astype(np.float)
  File "/home/wenhao/installs/conda/envs/Perceptual/lib/python3.6/site-packages/imageio/core/functions.py", line 160, in imread
    return file.read(index=0, **kwargs)
  File "/home/wenhao/installs/conda/envs/Perceptual/lib/python3.6/site-packages/imageio/core/legacy_plugin_wrapper.py", line 133, in read
    reader = self.legacy_get_reader(**kwargs)
  File "/home/wenhao/installs/conda/envs/Perceptual/lib/python3.6/site-packages/imageio/core/legacy_plugin_wrapper.py", line 103, in legacy_get_reader
    return self._format.get_reader(self._request)
  File "/home/wenhao/installs/conda/envs/Perceptual/lib/python3.6/site-packages/imageio/core/format.py", line 190, in get_reader
    return self.Reader(self, request)
  File "/home/wenhao/installs/conda/envs/Perceptual/lib/python3.6/site-packages/imageio/core/format.py", line 281, in __init__
    self._open(**self.request.kwargs.copy())
TypeError: _open() got an unexpected keyword argument 'flatten'

**Comment by thfylsty** [comment]
maybe you are chinese？

我就直接打中文了哈😂，随意点

从报错提示看，是imread出错，调用的是imageio接口。猜测是版本问题造成的。建议直接用opencv的库。替换成cv2.imread。

但其实这份代码已经非常古老了，新手建议直接干pytorch而不是死磕tensorflow

**Comment by thfylsty** [comment]
According to the error prompt, it is the error of imread, and the imageio interface is called. Guess the version problem. It is recommended to use the library of opencv directly. Replace with cv2.imread

But in fact, this code is very old, and novices suggest to do pytorch directly instead of screwing tensorflow.
